"""
main.py
--------
FastAPI application entry point.

WHAT THIS FILE DOES:
  1. Creates the FastAPI app instance
  2. Configures CORS middleware (allows Next.js frontend to call this API)
  3. Configures logging
  4. Registers all API routers with their URL prefixes
  5. Adds startup/shutdown lifecycle hooks

ROUTERS MOUNTED:
  /documents  → documents.py  (list, get, delete documents + health check)
  /ingest     → ingest.py     (upload files, ingest URLs)
  /query      → query.py      (RAG queries, streaming, agent, batch)

RUN IN DEVELOPMENT:
  poetry run uvicorn documind_backend.main:app --reload --port 8000

  Or with the dev alias:
  poetry shell
  uvicorn documind_backend.main:app --reload --port 8000

API DOCS (auto-generated by FastAPI):
  http://localhost:8000/docs      ← Swagger UI (interactive)
  http://localhost:8000/redoc     ← ReDoc (clean reading)
  http://localhost:8000/openapi.json ← raw OpenAPI schema
"""

import logging
import sys
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from documind_backend.config import settings
from documind_backend.api import documents, ingest, query, configuration
import documind_backend.core.retrieval.vectorstore as VectorStore

# ══════════════════════════════════════════════════════════════════════════════
# Logging setup
# ══════════════════════════════════════════════════════════════════════════════
# Configure logging before anything else so startup messages are captured.
# Format: "2024-01-15 10:23:45 | INFO     | [module] message"

logging.basicConfig(
    level=getattr(logging, settings.log_level.upper(), logging.INFO),
    format="%(asctime)s | %(levelname)-8s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger(__name__)


# ══════════════════════════════════════════════════════════════════════════════
# Lifespan — startup + shutdown hooks
# ══════════════════════════════════════════════════════════════════════════════


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Async context manager for startup and shutdown logic.

    STARTUP (code before `yield`):
      - Log configuration summary
      - Warm up ChromaDB connection (fail fast if unavailable)
      - Warm up Ollama connection (fail fast if unavailable)
      These ensure the app crashes immediately on startup if dependencies
      are missing — much better than cryptic errors on the first request.

    SHUTDOWN (code after `yield`):
      - Any cleanup (close DB connections, flush buffers, etc.)
      Currently nothing to clean up — ChromaDB and Ollama manage themselves.
    """
    # ── Startup ──────────────────────────────────────────────────────────────
    logger.info("=" * 60)
    logger.info("DocuMind Backend starting up")
    logger.info(f"  Environment:  {settings.app_env}")
    logger.info(f"  Chat model:   {settings.ollama_chat_model}")
    logger.info(f"  Embed model:  {settings.ollama_embedding_model}")
    logger.info(f"  Ollama URL:   {settings.ollama_base_url}")
    logger.info(
        f"  ChromaDB:     {settings.chroma_host}:{settings.chroma_port} (HTTP: {settings.chroma_use_http})"
    )
    logger.info(
        f"  Re-ranking:   {'enabled (FlashRank)' if settings.use_reranking else 'disabled'}"
    )
    logger.info(f"  LangSmith:    {'enabled' if settings.langchain_tracing_v2 else 'disabled'}")
    logger.info("=" * 60)

    # Warm up ChromaDB — creates collection if it doesn't exist
    try:
        VectorStore.get_vectorstore()
        count = VectorStore.get_chunk_count()
        logger.info(f"ChromaDB ready — {count} chunks in collection")
    except Exception as e:
        logger.error(f"ChromaDB startup failed: {e}")
        logger.error("Check that CHROMA_PERSIST_DIR is writable")
        raise

    # Warm up Ollama connection — verify the server is reachable
    try:
        import httpx

        async with httpx.AsyncClient() as client:
            response = await client.get(
                f"{settings.ollama_base_url}/api/tags",
                timeout=5.0,
            )
            response.raise_for_status()
            models = [m["name"] for m in response.json().get("models", [])]
            logger.info(f"Ollama ready — available models: {models}")

            # Verify required models are pulled
            required = {settings.ollama_chat_model, settings.ollama_embedding_model}
            missing = required - set(models)
            if missing:
                logger.warning(
                    f"Required Ollama models not found: {missing}. "
                    f"Run: ollama pull {' '.join(missing)}"
                )
    except Exception as e:
        logger.warning(
            f"Ollama not reachable at {settings.ollama_base_url}: {e}. "
            "Queries will fail until Ollama is started."
        )
        # Don't raise — allow the app to start even if Ollama isn't up yet.
        # This lets the ingest endpoint work for document management
        # while waiting for Ollama to start.

    logger.info("DocuMind is ready — listening for requests")

    yield  # ← app is running here

    # ── Shutdown ─────────────────────────────────────────────────────────────
    logger.info("DocuMind shutting down")


# ══════════════════════════════════════════════════════════════════════════════
# FastAPI application
# ══════════════════════════════════════════════════════════════════════════════

app = FastAPI(
    title="DocuMind API",
    description=(
        "AI-powered document intelligence backend. "
        "Upload documents, ask questions, get grounded answers with citations. "
        "Powered by LangChain, LangGraph, ChromaDB, and Ollama (llama3.2)."
    ),
    version="0.1.0",
    # lifespan replaces the deprecated on_event("startup") / on_event("shutdown")
    lifespan=lifespan,
    # Disable docs in production if you want (security hardening)
    docs_url="/docs" if not settings.is_production else None,
    redoc_url="/redoc" if not settings.is_production else None,
)


# ══════════════════════════════════════════════════════════════════════════════
# CORS middleware
# ══════════════════════════════════════════════════════════════════════════════
# CORS (Cross-Origin Resource Sharing) allows the Next.js frontend
# running on localhost:3000 to call this API on localhost:8000.
# Without CORS middleware, browsers block cross-origin requests.

app.add_middleware(
    CORSMiddleware,
    # Origins allowed to call this API.
    # In development: http://localhost:3000 (Next.js dev server)
    # In production:  your actual frontend domain (e.g. https://app.documind.io)
    allow_origins=settings.cors_origins_list,
    # Allow cookies and Authorization headers to be sent cross-origin
    allow_credentials=True,
    # HTTP methods the frontend can use
    allow_methods=["GET", "POST", "DELETE", "OPTIONS"],
    # Headers the frontend can send
    allow_headers=["Content-Type", "Authorization", "Accept"],
)


# ══════════════════════════════════════════════════════════════════════════════
# Router registration
# ══════════════════════════════════════════════════════════════════════════════
# Each router is a group of related endpoints defined in api/routes/.
# All endpoints from documents.py are prefixed with "" (root),
# ingest.py with "" (root), query.py with "" (root).
# Tags group them in the Swagger UI.

app.include_router(
    documents.router,
    tags=["Documents"],
)

app.include_router(
    ingest.router,
    tags=["Ingestion"],
)

app.include_router(
    query.router,
    tags=["Query"],
)

app.include_router(
    configuration.router,
    tags=["Configuration"],
)


# ══════════════════════════════════════════════════════════════════════════════
# Root endpoint
# ══════════════════════════════════════════════════════════════════════════════


@app.get("/", tags=["Root"])
async def root():
    """
    Root endpoint — confirms the API is running.
    Useful for a quick sanity check: curl http://localhost:8000/
    """
    return {
        "name": "DocuMind API",
        "version": "0.1.0",
        "status": "running",
        "docs": "/docs",
    }
